name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Trigger only when frontend files change

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "D:\Surya Study\Python\New folder\.vscode\Appoinment-booking-api\appointment-frontend-html"       # Path to your frontend folder
          output_location: ""             # No build output (plain HTML/CSS)
          app_build_command: ""           # Skip the build step
